# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 05:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.CharField(max_length=200)),
                ('money_off', models.CharField(default='', max_length=200)),
                ('date_off', models.DateTimeField(default=django.utils.timezone.now)),
                ('year_in_school', models.CharField(choices=[('Standart', 'Standert'), ('Normal', 'Normal'), ('Premium', 'Premium'), ('Platinum', 'Platinum')], default='Standart', max_length=10)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
