# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='transfer',
            name='tarif',
            field=models.CharField(choices=[('bronze', 'bronze'), ('silver', 'silver'), ('gold', 'gold'), ('platinum', 'platinum')], default='bronze', max_length=10),
        ),
    ]
