# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transuser', '0002_auto_20180506_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='procent',
            field=models.IntegerField(default=0),
        ),
    ]
