# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transuser', '0003_transfer_procent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='money_off',
            field=models.IntegerField(default=0),
        ),
    ]
