# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transuser',
            name='tarif',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transuser',
            name='money_on',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
