# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_auto_20180330_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='transuser',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
    ]
