# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_auto_20180331_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transuser',
            name='name_tarif',
            field=models.CharField(choices=[('FR', 'bronze'), ('SO', 'silver'), ('JR', 'gold'), ('SR', 'platinum')], default='FR', max_length=2),
        ),
    ]
