# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0008_auto_20180331_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='transuser',
            name='money',
            field=models.CharField(default='', max_length=200),
        ),
    ]
