# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0010_auto_20180331_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transuser',
            name='name_tarif',
        ),
        migrations.AlterField(
            model_name='transuser',
            name='money_off',
            field=models.CharField(default='100', max_length=200),
        ),
        migrations.AlterField(
            model_name='transuser',
            name='money_on',
            field=models.CharField(default='100', max_length=200),
        ),
        migrations.AlterField(
            model_name='transuser',
            name='tarif',
            field=models.CharField(default='100', max_length=200),
        ),
    ]
