# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0011_auto_20180331_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='transuser',
            name='name_tarif',
            field=models.CharField(choices=[('FR', 'bronze'), ('SO', 'silver'), ('JR', 'gold'), ('SR', 'platinum')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='transuser',
            name='money',
            field=models.CharField(default=100, max_length=200),
        ),
        migrations.AlterField(
            model_name='transuser',
            name='money_off',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transuser',
            name='money_on',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transuser',
            name='tarif',
            field=models.IntegerField(default=0),
        ),
    ]
